### ISSUE TITLE
Mailhog not catching emails

### ISSUE THREAD

**Issue by FlorianMoser** [weprovide/valet-plus#397] opened 2019-08-26 15:38 UTC
Mailhog is suddenly no longer catching emails. `valet logs mailhog` displays an error every 10 seconds:

```
19/08/26 17:35:45 Using in-memory storage
2019/08/26 17:35:45 [SMTP] Binding to address: 0.0.0.0:1025
[HTTP] Binding to address: 0.0.0.0:8025
2019/08/26 17:35:45 Serving under http://0.0.0.0:8025/
2019/08/26 17:35:45 [SMTP] Error listening on socket: listen tcp 0.0.0.0:1025: bind: address already in use
```

I tried `valet fix`, restarting OSX, restarting valet, `valet install` and uninstalling/re-installing MailHog.

Any ideas how to solve this problem?

**Comment by Neodork** [comment] 2019-08-26 18:15
Look for the service that's using 8025 (possibly lingering service from mailhog itself). And then kill it and `valet restart`.

Or you could try and kill the service on a tcp port [using some cli magic](https://stackoverflow.com/a/36917850/4442333).

**Comment by FlorianMoser** [comment] 2019-08-26 19:08
I have only Mailhog, listening on port 1025/8025 (tried with `sudo lsof -nP -i4TCP:1025 | grep LISTEN`), and I also tried killing it. But it restarts itself right away. Thats where I uninstalled Mailhog, killed the PID and tried `valet install` (which then re-installs Mailhog). But then I have the error again.

**Comment by Neodork** [comment] 2019-08-26 21:29
What kind of application is trying to send the mails? Are other applications actually getting caught by mailhog?

**Comment by FlorianMoser** [comment] 2019-08-27 05:40
> What kind of application is trying to send the mails?

Laravel. It bypasses Mailhog and tries to directly connect to a SMTP server. Of course I can set the SMTP server to 0.0.0.0:1025, and Mailhog catches the mails. But I thought, outgoing Mails would be catched at PHP sendmail level.

> Are other applications actually getting caught by mailhog?

I just installed WordPress for testing purposes, and its emails are caught. Still getting the error message in the log every 10 seconds, but it seems to work with WP.

If that's the intended behaviour, I will close the issue.

**Comment by Neodork** [comment] 2019-08-27 14:20
Depending on the application, if it's targeting another SMTP server it will not run though 0.0.0.0:1025 and thus the mail won't be caught. You need to set it up to fire upon the local port. Closing ticket as working as intended.

**Closed by Neodork** 2019-08-27 14:20 UTC
Labels: 1.0.x

**Comment by keferboeck** [comment] 2021-06-01 22:11
I had the same issue, i had WeVPN running (chrome extension). Once I disconnected everything was well.
