### ISSUE TITLE
POST requests becomes GET

### ISSUE THREAD

**Issue by wiardvanrij** [weprovide/valet-plus#185] opened 2018-06-05 13:20 UTC
Since the latest release POST requests are handled as GET requests. 

You can notice this when writing a decent API using strict methods. On the latest version I receive a HTTP 405 Method Not Allowed error on my POST requests. Saying method GET is not allowed. 

When downgrading from 1.0.16 to 1.0.15 this issue is resolved.

**Comment by Neodork** [comment] 2018-06-05 13:51
@wiardvanrij What driver are you using?

**Comment by wiardvanrij** [comment] 2018-06-05 14:59
@Neodork Symfony driver, non custom

**Comment by Neodork** [comment] 2018-06-08 17:11
@wiardvanrij I am not seeing an changes within the Symfony driver for over a year. Could the cause be webserver or application related?

**Comment by samgranger** [comment] 2018-06-11 09:15
This is quite odd, could you give 1.0.17 a try?

**Comment by samgranger** [comment] 2018-07-13 21:38
Closing this issue due to receiving no further updates. Please let us know if this is still an issue.

**Closed by samgranger** 2018-07-13 21:38 UTC
