### ISSUE TITLE
Magento 2 Admin 502 Bad Gateway

### ISSUE THREAD

**Issue by cgartner-redstage** [weprovide/valet-plus#379] opened 2019-07-04 13:35 UTC
I updated my valet for the last update before I cleaned up my last installation of valet plus.

All is working fine in the frontend of the store, but when I try login in the admin I receive a 502 Bad Gateway error.

I tried the #322 responses but not is working, this is my logs:

```
==> /Users/cagartner/.valet/Log/mysql.log <==
2019-07-04T13:33:30.548710Z 49 [Note] Aborted connection 49 to db: 'tweezerman2' user: 'root' host: 'localhost' (Got an error reading communication packets)

==> /Users/cagartner/.valet/Log/nginx-error.log <==
2019/07/04 10:33:30 [error] 13960#0: *46 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: tweezermanm2.test, request: "GET /admin_13o8fj/admin/dashboard/index/key/13f939ce7d9c42acc9f1829ec2b0db1481d535c8a12a88175c01362013d4c392/ HTTP/2.0", upstream: "fastcgi://unix:/Users/cagartner/.valet/valet.sock:", host: "tweezermanm2.test", referrer: "https://tweezermanm2.test/admin_13o8fj/admin/index/index/key/b636e21558272358f4a58c1e162c13dff8f44a557d0b2ea5df591164b9861d08/"
```

I tried to increase the `fastcgi_read_timeout` but without success.

Tried to reinstall my mysql, but not solved...

Anyone can help me?

**Comment by cgartner-redstage** [comment] 2019-07-04 16:06
Tried to add the following lines to `/usr/local/etc/nginx/nginx.conf` within `http {}`
```
   fastcgi_buffering on;
   fastcgi_buffers 4 256k;
   fastcgi_buffer_size 128k;
```
not worked

**Comment by vadim-shulyak** [comment] 2019-07-04 19:33
Have the same issue.
Also see php-fpm log (valet log php-fpm): 

```
WARNING: [pool www] child 27910 exited on signal 11 (SIGSEGV) after 532.219031 seconds from start
NOTICE: [pool www] child 31165 started
```

**Comment by cagartner** [comment] 2019-07-05 12:08
My versions:
nginx version: nginx/1.17.1

I think this is a NGINX problem because the error occurs with different PHP versions.

**Comment by cgartner-redstage** [comment] 2019-07-05 12:26
@vadim-shulyak what is the version of your nginx?

**Comment by vadim-shulyak** [comment] 2019-07-06 10:17
@cagartner 
nginx version: nginx/1.17.1

**Comment by vadim-shulyak** [comment] 2019-07-06 20:11
@cgartner-redstage fixed for me, the cause was in the curl-openssl
See: https://github.com/laravel/valet/issues/791#issuecomment-508682547

**Comment by cagartner** [comment] 2019-07-07 02:14
@vadim-shulyak awesome, worked fine here too.
Thank you!

**Comment by amarroni** [comment] 2019-07-08 19:20
@cgartner-redstage @vadim-shulyak thank you so much for your findings. Here is what I found in my case:
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/e47f3e2682fa3d8a6ee58ded40718a1326e08a6d/Formula/curl-openssl.rb --from-source`

throw a error:
Error: invalid option: --from-source 

Then I try:
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/e47f3e2682fa3d8a6ee58ded40718a1326e08a6d/Formula/curl-openssl.rb --build-from-source`

Evrething works fine.
In my case Fixed a Segmentation fault: 11.

Best,
Alejandro.

**Comment by goranhorvathr** [comment] 2019-07-11 15:54
Nothing from here worked for me.

**Comment by wessel-techtribe-nl** [comment] 2019-10-28 12:35
With valet-php@7.2 this results in my installation in a:

`php -v
dyld: Library not loaded: /usr/local/opt/curl-openssl/lib/libcurl.4.dylib
  Referenced from: /usr/local/bin/php
  Reason: Incompatible library version: php requires version 11.0.0 or later, but libcurl.4.dylib provides version 10.0.0
`
Any suggestions on how to proceed? Because problems is the same: working frontend magento but admin results in 502 Bad Gateway

**Comment by frqnck** [comment] 2019-11-07 12:58
Same issue here too. Keep getting this dreaded 502 when accessing the admin panel. Nothing above has worked. To me it looks like an issue with MySQL rather than Nginx. See logs below:

```
~/.valet/Log/nginx-error.log:
2019/11/06 19:14:31 [error] 341#0: *52681 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /admin/admin/index/index/key/../"

~/.valet/Log/mysql.log:
2019-11-06T19:14:31.750089Z 1544 [Note] Aborted connection 1544 to db: 'magento' user: 'magento' host: 'localhost' (Got an error reading communication packets)
```

Has anyone got this working on Catalina? If so could you share your `my.cnf` and `ngixfile.conf?

**Comment by Neodork** [comment] 2020-02-07 11:32
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team

**Closed by Neodork** 2020-02-07 11:32 UTC
Labels: 1.0.x

**Comment by motilalmb** [comment] 2024-11-15 11:46
Hi all 
I get the same error 502 for some specific customer when I do logging as customer for admin
