### ISSUE TITLE
Bug: <valet successfully started not working>

### ISSUE THREAD

**Issue by farmaworld** [weprovide/valet-plus#560] opened 2021-01-09 10:49 UTC
i have this situation on my mac Big Sur 11.1
don't ping *.test
which php

/usr/local/bin/php

php -v

PHP 7.2.34 (cli) (built: Oct  1 2020 16:05:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34, Copyright (c) 1999-2018, by Zend Technologies

brew services list

Name          Status  User     Plist
dnsmasq       stopped          
httpd         stopped          
httpd-bc      stopped          
mailhog       stopped          
mysql@5.7     started raffaele /Users/raffaele/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx         stopped          
redis         stopped          
valet-php@5.6 stopped          
valet-php@7.1 stopped          
valet-php@7.2 started raffaele /Users/raffaele/Library/LaunchAgents/homebrew.mxcl.valet-php@7.2.plist
valet-php@7.3 started raffaele /Users/raffaele/Library/LaunchAgents/homebrew.mxcl.valet-php@7.3.plist

brew info php

php: stable 8.0.1 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd ✔, pkg-config ✔
Required: apr ✔, apr-util ✔, argon2 ✔, aspell ✔, autoconf ✔, curl ✔, freetds ✔, gd ✘, gettext ✔, glib ✔, gmp ✔, icu4c ✔, krb5 ✔, libffi ✔, libpq ✔, libsodium ✔, libzip ✔, oniguruma ✘, openldap ✔, openssl@1.1 ✔, pcre2 ✔, sqlite ✔, tidy-html5 ✔, unixodbc ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.0/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 39,490 (30 days), 160,084 (90 days), 600,276 (365 days)
install-on-request: 38,783 (30 days), 157,058 (90 days), 576,318 (365 days)
build-error: 0 (30 days)

Stopping `valet-php@7.2`... (might take a while)
==> Successfully stopped `valet-php@7.2` (label: homebrew.mxcl.valet-php@7.2)
==> Successfully started `valet-php@7.2` (label: homebrew.mxcl.valet-php@7.2)

**Comment by mizzimizzi** [comment] 2021-01-11 15:42
Same issue here,
it seems that starting the services manually everything works.

**Comment by harlet** [comment] 2021-01-12 11:17
A fix will be released soon. https://github.com/weprovide/valet-plus/pull/554

**Comment by farmaworld** [comment] 2021-01-15 15:32
> Same issue here,
> it seems that starting the services manually everything works.

for me start, but don't work anything
please

**Comment by mizzimizzi** [comment] 2021-01-16 14:23
> > Same issue here,
> > it seems that starting the services manually everything works.
> 
> for me start, but don't work anything
> please

Make sure each service is started with the right privileges. For example:
![valets](https://user-images.githubusercontent.com/39195647/104814364-c7372b00-580e-11eb-9e0e-eda4b37f1502.png)

**Comment by farmaworld** [comment] 2021-01-16 17:28
Name          Status  User     Plist
dnsmasq       stopped          
httpd         stopped          
httpd-bc      stopped          
mailhog       stopped          
mysql@5.7     started raffaele /Users/raffaele/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx         stopped          
redis         stopped          
valet-php@5.6 stopped          
valet-php@7.1 stopped          
valet-php@7.2 started raffaele /Users/raffaele/Library/LaunchAgents/homebrew.mxcl.valet-php@7.2.plist
valet-php@7.3 started raffaele /Users/raffaele/Library/LaunchAgents/homebrew.mxcl.valet-php@7.3.plist

**Comment by farmaworld** [comment] 2021-01-18 17:21
this is my services
[
<img width="736" alt="Schermata 2021-01-18 alle 18 19 55" src="https://user-images.githubusercontent.com/12223528/104946106-d9a19800-59b9-11eb-9dff-941208c9850a.png">
](url)

**Comment by mizzimizzi** [comment] 2021-01-18 18:45
Try doing it this way:
`sudo brew services stop --all && brew services stop --all`
make sure every service is stopped. Then
`sudo brew services start dnsmasq`
`brew services start mailhog`
`brew services start mysql@5.7`
`sudo brew services start nginx`
`brew services start redis`
`sudo brew services start valet-php@7.3`

**Comment by farmaworld** [comment] 2021-01-19 08:51
i'm try but don't pin
<img width="732" alt="Schermata 2021-01-19 alle 09 50 38" src="https://user-images.githubusercontent.com/12223528/105010304-d64ef080-5a3b-11eb-837b-bb8b757afd53.png">

**Comment by farmaworld** [comment] 2021-01-19 08:52
but initialization of site work
<img width="564" alt="Schermata 2021-01-19 alle 09 51 57" src="https://user-images.githubusercontent.com/12223528/105010435-fe3e5400-5a3b-11eb-8cbe-42cf55e9e88a.png">

**Comment by farmaworld** [comment] 2021-02-08 07:50
nothing?
please

**Comment by mizzimizzi** [comment] 2021-02-08 09:01
Hi,
I can't understand what the problem is. We need a better description. Have you tried with the suggested steps?

**Comment by farmaworld** [comment] 2021-02-08 09:11
valet is started but i have 502 bad gateway error

**Comment by mizzimizzi** [comment] 2021-02-08 09:17
I don't think it's a Valet issue.
Have you checked the logs?

**Comment by farmaworld** [comment] 2021-02-08 09:17
<img width="733" alt="Schermata 2021-02-08 alle 10 16 49" src="https://user-images.githubusercontent.com/12223528/107199551-e16fbd80-69f6-11eb-9646-5e08c006b456.png">

**Comment by farmaworld** [comment] 2021-02-08 09:19
> I don't think it's a Valet issue.
> Have you checked the logs?

what log?
please help me

**Comment by mizzimizzi** [comment] 2021-02-08 09:39
The Nginx logs
`valet logs nginx`.
Also you can try to create a simple HTML page and check if valet can serve this page.

**Comment by farmaworld** [comment] 2021-02-08 18:51
2021/02/08 19:49:47 [crit] 4170#0: *8 connect() to unix:/Users/raffaele/.valet/valet.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: sitolocale.test, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/Users/raffaele/.valet/valet.sock:", host: "sitolocale.test"
2021/02/08 19:49:47 [crit] 4168#0: *10 connect() to unix:/Users/raffaele/.valet/valet.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: sitolocale.test, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://unix:/Users/raffaele/.valet/valet.sock:", host: "sitolocale.test", referrer: "https://sitolocale.test/"
2021/02/08 19:50:50 [crit] 4170#0: *8 connect() to unix:/Users/raffaele/.valet/valet.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: sitolocale.test, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/Users/raffaele/.valet/valet.sock:", host: "sitolocale.test"

**Comment by farmaworld** [comment] 2021-02-13 07:20
please help me

**Comment by diazwatson** [comment] 2021-11-26 09:37
valet logs nginx

```
2021/11/26 09:33:14 [crit] 50709#0: *1 connect() to unix:/Users/dtrump/.valet/valet.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/Users/dtrump/.valet/valet.sock:", host: "localhost"
2021/11/26 09:33:14 [crit] 50709#0: *1 connect() to unix:/Users/dtrump/.valet/valet.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/Users/dtrump/.valet/valet.sock:", host: "localhost", referrer: "http://localhost/"
```

brew services list
```
Name          Status  User  File
dnsmasq       stopped
httpd         stopped
mailhog       started dtrump ~/Library/LaunchAgents/homebrew.mxcl.mailhog.plist
mysql@5.7     started dtrump ~/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx         stopped
php           stopped
redis         started dtrump ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
valet-php@7.3 stopped
```

**Comment by mischabraam** [comment] 2023-10-16 08:29
The 502 might be solved with https://github.com/weprovide/valet-plus/issues/379

**Closed as completed by mischabraam** 2023-10-16 08:29 UTC
Labels: Bug, Needs review
