### ISSUE TITLE
Valet Plus not working on Mac Silicone (M1 Chip CPU, new Mac devices)

### ISSUE THREAD

**Issue by stefan1294** [weprovide/valet-plus#572] opened 2021-03-31 09:48 UTC
- [ X ] I've checked the issue queue and could not find anything similar to my bug.
- [ X ] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [ X ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Valet Plus isn't working on Mac Silicone due to hard coded paths in the old Valet version that Valet Plus is using. /usr/local/bin folder are for Intel Chips. The M1 Chips are using /opt/homebrew.

**What was supposed to happen?**
No errors about missing /usr/local/bin folders.

**What actually happened?**
Errors about missing /usr/local/bin folders

**How to reproduce this?**
Install valet-plus and run valet fix. You'll notice it'll look for pear config in the /usr/local/bin folder right away. Run valet install and you'll get the errors

**What is the solution?**
Either add support for the /opt/homebrew folders (as far as I know), or **_update_** to the latest valet version which supports Silicone.

**Sources**
https://github.com/laravel/valet/issues/1023

**Comment by leewillis77** [comment] 2021-04-01 09:02
Duplicate of #568

**Closed as completed** 2022-02-08 15:32 UTC
Labels: Bug, Needs review
