### ISSUE TITLE
Bug: New Valet+ fresh installation doesn't work

### ISSUE THREAD

**Issue by ezequielalba** [weprovide/valet-plus#461] opened 2020-02-13 00:05 UTC
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
A new fresh installation gives PECL problems that I was unable to fix with any other bug/issue already open/closed within the repo.

**What was supposed to happen?**
`valet install` should do a installation without any problems

**What actually happened?**
No matter what updates or removals o reinstalls you do with brew or valet commands, PECL fails every time.

**How to reproduce this?**
Pretty easy, just install it. `brew services start valet-php@7.2` `valet fix` `valet install` boom! breaks. 

**What is the solution?**
To work how it's supposed to :) 

**Sources**
ISSUE:
[php] Checking for errors within the php installation...
[nginx] Stopping
[valet-php@7.2] Stopping
[mysql@5.7] Stopping
[redis] Stopping
[devtools] Installing tools
[devtools] wp-cli already installed
[devtools] pv already installed
[devtools] geoip already installed
[devtools] zlib already installed
[binaries] Installing binaries
[BREW TAP] henkrehorst/php already installed
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions

**In Pecl.php line 146:**
**Could not find installation path for: apcu**
**No releases available for package "pecl.php.net/apcu"**
**install failed**

- `brew reinstall openssl` doesn't work
- `pecl channel-update pecl.php.net` doesn't work
- `Reinstall` everything again and `restart` computer doesn't work.

Thanks.

**Comment by ezequielalba** [comment] 2020-02-13 00:16
Using this fix: https://github.com/weprovide/valet-plus/issues/457#issuecomment-583424558

Shows same error: (Although it went longer within the installation)
[php] Checking for errors within the php installation...
[nginx] Stopping
[valet-php@7.2] Stopping
[mysql@5.7] Stopping
[redis] Stopping
[devtools] Installing tools
[wp-cli] Installing
[pv] Installing
[geoip] Installing
[zlib] Installing
[binaries] Installing binaries
[binaries] magerun not found, installing from: https://files.magerun.net/n98-magerun-1.103.1.phar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5383k  100 5383k    0     0   339k      0  0:00:15  0:00:15 --:--:--  433k
[binaries] magerun installed to: /usr/local/bin/magerun
[binaries] magerun2 not found, installing from: https://files.magerun.net/n98-magerun2-3.2.0.phar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5374k  100 5374k    0     0   605k      0  0:00:08  0:00:08 --:--:--  734k
[binaries] magerun2 installed to: /usr/local/bin/magerun2
[binaries] drush not found, installing from: https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600  100   600    0     0   1787      0 --:--:-- --:--:-- --:--:--  1791
100  303k  100  303k    0     0   343k      0 --:--:-- --:--:-- --:--:--  343k
[binaries] drush installed to: /usr/local/bin/drush
[BREW TAP] henkrehorst/php already installed
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions

In Pecl.php line 146:

  Could not find installation path for: apcu

  No releases available for package "pecl.php.net/apcu"
  install failed

**Comment by admanesachin** [comment] 2020-02-13 16:54
I can confirm this issue happens on a fresh install on MacOs and php 7.3. Disabling apcu, yaml and geoip extensions in Pecl.php will not help either. I get a valet successfully installed message but when i hit the domain in the browser i'm getting a "site refused to connect". Did valet park on the directory and valet domain test but nothing helps. Can someone assist in this frustrating process?

**Comment by ak077** [comment] 2020-02-14 04:08
I am having same issue.

**Comment by admanesachin** [comment] 2020-02-14 17:31
@Neodork can you verify this issue and suggest solutions?

**Comment by bartdominiak** [comment] 2020-02-15 08:54
This helps me - https://github.com/weprovide/valet-plus/issues/423#issuecomment-560128117

**Comment by ak077** [comment] 2020-02-15 18:58
> This helps me - [#423 (comment)](https://github.com/weprovide/valet-plus/issues/423#issuecomment-560128117)

This worked thank you ! 

@admanesachin you might wanna try it too

**Comment by admanesachin** [comment] 2020-02-18 17:16
Yes that works for me too. Thank you everyone.

**Comment by Neodork** [comment] 2020-02-19 14:49
@admanesachin As I mention in https://github.com/weprovide/valet-plus/issues/423#issuecomment-560128117 I wouldn't recommend using the workaround over the actual solution. That being said I can imagine finding the actual problem and solution to these kind of problems is difficult. 

I would personally not implement the workaround. But if you're stuck and unable to find the solution or join slack to ask one of the contributors to help you out. Then you might want to consider implementing the workaround.

**Comment by ezequielalba** [comment] 2020-02-21 21:08
@Neodork What more stacktraces/errors popping out do you need? I think I posted and specified really well the issue. However, let me know how I can help. Do you need versions of packages? Any other data? 

In my opinion, the fix must come from the install script when the PECL is triggered, perhaps needs update? perhaps the new OS versions require a different path or packages? I don't know further more, this are just logic-random thoughts, not my field.

Thanks!

**Comment by Igloczek** [comment] 2020-03-26 19:06
For me `brew switch openssl 1.0.2s` help with refused connections problems.

**Comment by israelguido** [comment] 2020-03-31 16:59
I have the same error =/

**Comment by philiprabbett** [comment] 2020-06-09 13:43
I've switched to `valet-php@7.4` rather than `valet-php@7.2` for the install (skipping `valet fix`) and it installs with the exception of the elasticsearch stub bug #392. Once that's fixed, all is well... fresh install.

**Comment by Krielkip** [comment] 2020-07-22 08:59
The fix in:  https://github.com/weprovide/valet-plus/issues/492#issuecomment-647420696  worked for me

**Comment by Neodork** [comment] 2020-11-06 20:20
Closing as the fix in https://github.com/weprovide/valet-plus/issues/492#issuecomment-647420696 is the correct solution. I will discuss a fix in the brew formula for this.

**Closed by Neodork** 2020-11-06 20:20 UTC
Labels: Bug, Input needed

**Comment by Igloczek** [comment] 2020-11-09 09:12
@Neodork is there a chance to create a list of known bugs and fixes like this, in form of some Wiki or part of README?
It's kinda frustrating that every person that is doing clean install need to dig into issues to find a solution for a common problem.
