### ISSUE TITLE
Unable to upgrade 

### ISSUE THREAD

**Issue by mmeester** [weprovide/valet-plus#147] opened 2018-04-17 09:38 UTC
When running `composer global require weprovide/valet-plus:1.0.13` I'm getting the following error

```
-> % composer global require weprovide/valet-plus:1.0.13
Changed current directory to 
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for weprovide/valet-plus 1.0.13 -> satisfiable by weprovide/valet-plus[1.0.13].
    - Conclusion: remove sebastian/version 1.0.6
    - Conclusion: don't install sebastian/version 1.0.6
    - weprovide/valet-plus 1.0.13 requires sebastian/version ^2.0 -> satisfiable by sebastian/version[2.0.0, 2.0.1].
    - Can only install one of: sebastian/version[2.0.0, 1.0.6].
    - Can only install one of: sebastian/version[2.0.1, 1.0.6].
    - Installation request for sebastian/version (locked at 1.0.6) -> satisfiable by sebastian/version[1.0.6].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by Neodork** [comment] 2018-04-26 15:38
@mmeester Could you show us the output of `composer global show -i`. This is mostlikely caused by having laravel/valet installed.

**Comment by mmeester** [comment] 2018-04-30 06:36
This is my output, I don't see laravel/valet anywhere:

```
container-interop/container-interop 1.2.0   Promoting the interoperability of container objects (DIC, SL, etc.)
doctrine/instantiator               1.1.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
illuminate/container                v5.6.16 The Illuminate Container package.
illuminate/contracts                v5.6.16 The Illuminate Contracts package.
jolicode/jolinotif                  v1.3.0  Send desktop notifications on Windows, Linux, MacOS.
mnapoli/silly                       1.5.1   Silly CLI micro-framework based on Symfony Console
nategood/httpful                    0.2.20  A Readable, Chainable, REST friendly, PHP HTTP Client
php-di/invoker                      1.3.3   Generic and extensible callable invoker
phpdocumentor/reflection-common     1.0.1   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   4.3.0   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver         0.4.0
phpspec/prophecy                    1.7.5   Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage           2.2.4   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator           1.4.5   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template           1.2.1   Simple template engine.
phpunit/php-timer                   1.0.9   Utility class for timing
phpunit/php-token-stream            1.4.12  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     4.8.36  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects        2.3.8   Mock Object library for PHPUnit
psr/container                       1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/log                             1.0.2   Common interface for logging libraries
psr/simple-cache                    1.0.1   Common interfaces for simple caching
richdynamix/magestead               2.2.2   Magestead - A command line installer for Magento Vagrant environments
sebastian/comparator                1.2.4   Provides the functionality to compare PHP values for equality
sebastian/diff                      1.4.3   Diff implementation
sebastian/environment               1.3.8   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  1.2.2   Provides the functionality to export PHP variables for visualization
sebastian/global-state              1.1.1   Snapshotting of global state
sebastian/recursion-context         1.0.5   Provides functionality to recursively process PHP variables
sebastian/version                   1.0.6   Library that helps with managing the version number of Git-hosted PHP projects
symfony/console                     v3.4.8  Symfony Console Component
symfony/debug                       v4.0.8  Symfony Debug Component
symfony/polyfill-mbstring           v1.7.0  Symfony polyfill for the Mbstring extension
symfony/process                     v3.4.8  Symfony Process Component
symfony/yaml                        v3.4.8  Symfony Yaml Component
tightenco/collect                   v5.4.33 Collect - Illuminate Collections as a separate package.
webmozart/assert                    1.3.0   Assertions to validate method input/output with nice error messages.
weprovide/valet-plus                1.0.11  Blazing fast macOS PHP development environment
```

**Comment by Neodork** [comment] 2018-04-30 08:01
Please remove `sebastian/version` and try to install `weprovide/valet-plus` again.

**Comment by samgranger** [comment] 2018-05-14 08:41
Has this issue been resolved @mmeester?

**Comment by samgranger** [comment] 2018-05-14 12:18
Closing this issue, please open a new ticket if you're still encountering issues.

**Closed by samgranger** 2018-05-14 12:18 UTC

**Comment by mmeester** [comment] 2018-05-14 12:45
Yest, it was magestead that was conflicting
