### ISSUE TITLE
Cannot extend custom drivers because of dynamic loading

### ISSUE THREAD

**Issue by TommyKolkman** [weprovide/valet-plus#264] opened 2018-11-12 14:14 UTC
We've got a custom driver setup for Magento 2 in our project root as LocalValetDriver.php. 

This class extends Magento2ValetDriver, but since [this](https://github.com/weprovide/valet-plus/pull/237/commits/345d080afebdcca92bb9c2e747d95b6d27e02416) PR was merged, we are unable to extend, the driver is not on the require list anymore.

As a temp fix we now patch cli/drivers/require.php, but surely there's a better option?

**Comment by cagartner** [comment] 2018-11-14 10:46
Need to verify this, we need to rollback the PR manually to make work the LocalValetDriver.php

**Comment by jellesiderius** [comment] 2018-11-30 09:49
Can confirm, having the same issue!

**Comment by JPry** [comment] 2018-12-19 14:46
I'm also having this problem. This was caused by #237.

**Comment by samgranger** [comment] 2019-02-27 13:12
This has been fixed in the latest version of Valet+, see https://github.com/weprovide/valet-plus/commit/35cdc69047e17a92007edeed6ff5c15727e2e065

**Closed by samgranger** 2019-02-27 13:12 UTC
