### ISSUE TITLE
Bug: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.66.dylib

### ISSUE THREAD

**Issue by rav-redchamps** [weprovide/valet-plus#491] opened 2020-05-31 14:23 UTC
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Receiving 502 bad gateway error while accessing any site

log file: /usr/local/var/log/php-fpm.log

contains error

dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.66.dylib
  Referenced from: /usr/local/opt/valet-php@7.2/sbin/php-fpm
  Reason: image not found

Directory /usr/local/opt/icu4c/lib seems to be containing version 67 instead but valet-php@7.2 seems to be referencing version 66

**content of folder "/usr/local/opt/icu4c/lib" are:**

icu			libicuio.67.1.dylib	libicutu.67.dylib
libicudata.67.1.dylib	libicuio.67.dylib	libicutu.a
libicudata.67.dylib	libicuio.a		libicutu.dylib
libicudata.a		libicuio.dylib		libicuuc.67.1.dylib
libicudata.dylib	libicutest.67.1.dylib	libicuuc.67.dylib
libicui18n.67.1.dylib	libicutest.67.dylib	libicuuc.a
libicui18n.67.dylib	libicutest.a		libicuuc.dylib
libicui18n.a		libicutest.dylib	pkgconfig
libicui18n.dylib	libicutu.67.1.dylib

**Comment by dannylepage** [comment] 2020-05-31 15:26
I'm also encountering this problem which has arisen since running `brew install node`. It appears Node depends on **icu4c** which is at **67.1**.

I'm thinking reinstalling php should do the job. Not sure on the safest why to update php on valet+, mind.

**Comment by rav-redchamps** [comment] 2020-05-31 15:35
I think icu4c 67.1 is released recently and valet-php@7.2 and other version depends on version 66.1 that is creating problem

I am trying icu4c version revert to 66.1 

You may try below commands

cd $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core/Formula

git checkout -b icu4c 22fb699a417093cd1440857134c530f1e3794f7d

brew reinstall ./icu4c.rb

**Comment by dannylepage** [comment] 2020-05-31 15:37
Hi thanks for the idea @rav-redchamps, I did try this already but then node is broken.

**Comment by dingo-d** [comment] 2020-05-31 16:43
@rav-redchamps This happened to me and I reverted it, now it works.

I'm on node 12 and it works for me (and yarn which is using the icu4u lib).

I've opened an issue in the repo for the [valet PHP](https://github.com/henkrehorst/homebrew-php/issues/72), hopefully, this will be fixed somehow upstream.

**Comment by ityetti** [comment] 2020-05-31 22:15
@rav-redchamps try another way
```
brew uninstall valet-php@7.3
brew install --build-from-source valet-php@7.3
brew link --force valet-php@7.3
```
And reboot your Mac.

**Comment by alexryans** [comment] 2020-06-01 10:37
Hi, has anyone got a definite fix for this? I've tried all the above and, as @dannylepage states, reverting to 66.1 breaks node, which is still asking for 67.1 after fixing Valet v66 requirement.

**Comment by henkrehorst** [comment] 2020-06-01 13:32
Hi @all,

The problem is with the valet-php bottles, i am rebuilding them now within 3 hours all php version are working again.

**Comment by dingo-d** [comment] 2020-06-01 14:22
I can confirm that it's working. I've reinstalled icu4c to latest version, removed `valet-php@7.3` and did

```bash
brew uninstall valet-php@7.3
brew install --build-from-source valet-php@7.3
brew link --force valet-php@7.3
```

And it works 🙂

**Comment by macist-m** [comment] 2020-06-01 16:14
While installing valet-php@7.2 or 7.3 

It is stuck here

`==> Patching
patching file acinclude.m4
Hunk #1 succeeded at 446 (offset 5 lines).
Hunk #2 succeeded at 461 (offset 5 lines).
Hunk #3 succeeded at 496 (offset 5 lines).
Hunk #4 succeeded at 508 (offset 5 lines).
patch unexpectedly ends in middle of line
Hunk #5 succeeded at 2529 with fuzz 1 (offset 110 lines).
==> ./buildconf --force
==> ./configure --prefix=/usr/local/Cellar/valet-php@7.2/7.2.30_3 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/valet-php/7.2 --with-config-file-pa`

**Comment by Inevix** [comment] 2020-06-02 06:01
How to run valet fix with prefix --build-from-source for php?

**Comment by ityetti** [comment] 2020-06-02 11:22
@Inevix you don't need to run valet with prefix. You'll must to delete php and build it from the source, look to the my comment above.

**Comment by complexthings** [comment] 2020-06-17 12:14
Followed @dannylepage's advice and fixed it quickly:

```bash
brew upgrade valet-php@<version> #<version> being 5.6, 7.1, 7.2, or 7.3

valet restart
```

**Comment by stefan-h-singer** [comment] 2020-06-18 08:31
Confirming that upgrading the php package solves the issue (in my case for php 7.0).

**Comment by alexryans** [comment] 2021-04-26 10:19
I think this issue may have reared its head again. @henkrehorst, do the valet-php bottles need rebuilding to support v68?

**Closed** 2024-02-16 11:44 UTC
Labels: Bug, Needs review
