### ISSUE TITLE
Sometimes valet.sock file doesn't refresh

### ISSUE THREAD

**Issue by imadphp** [weprovide/valet-plus#177] opened 2018-05-30 12:51 UTC

**Comment by Neodork** [comment] 2018-05-30 13:20
Hey could you please add instructions for reproducing the issue?

**Comment by abbatis** [comment] 2018-05-30 13:57
Hi @Neodork. I'm not sure how to reproduce this issue. However, I'll work on this myself, later this week. For more info please check Gitter. I discussed this with @samgranger

**Comment by Neodork** [comment] 2018-05-30 14:03
Sure thing lets leave it open to see if someone else has more insight on it. My guess would be something permission related.

**Comment by abbatis** [comment] 2018-05-30 14:10
Basically tried everything. I even chmod'ed valet.sock tot 777 Maybe it doesn't hurt to always explicitly `unlink` valet.sock when switching. That was initially my idea, because removing this file basically forces a refresh. I don't have this problem on my machine, but several colleagues do and I'm trying to fix it for them.

**Comment by Neodork** [comment] 2018-05-30 14:18
You could try something like `sudo brew services restart php@{Version}` and see if that regenerates is correctly. Notice I used sudo there.

**Comment by abbatis** [comment] 2018-05-30 14:33
Nope, doesn't work unfortunately. How'd you feel about an explicit unlink on every switch? Shall I implement that. It's about the only idea I have. 😄

**Comment by Neodork** [comment] 2018-05-31 10:39
I'd like to know the cause of the problem first before we implement a workaround like that. Lets leave this open for now and if the problem persist we will have to either implement the workaround or spend more time researching the cause.

**Comment by samgranger** [comment] 2018-07-14 02:50
Could you try our new 1.0.19 release to see if it solves this issue?

**Comment by Neodork** [comment] 2020-02-07 11:19
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team

**Closed by Neodork** 2020-02-07 11:19 UTC
Labels: 1.0.x
