### ISSUE TITLE
Issues installing valet 2.0 on new catalina machine due to openssl erros pecl

### ISSUE THREAD

**Issue by kayintveen** [weprovide/valet-plus#423] opened 2019-11-22 14:11 UTC
Installing went smooth untill i needed to install the pecl modules.
in short the error is:

`Connection to ssl://pecl.php.net:443 failed:`

I tried reinstalling openssl

`brew reinstall openssl`

There are also some obscure options to download .pem files and installing them in the used directory. But that also did not work. I currently have eveything like it should be but not able to pass anything pecl related. not listing, not search and certanly not installing. 

```
❯ pecl update-channels
Updating channel "doc.php.net"
Update of Channel "doc.php.net" succeeded
Updating channel "pear.php.net"
Channel "pear.php.net" is not responding over http://, failed with message: Connection to `ssl://pear.php.net:443' failed:
Trying channel "pear.php.net" over https:// instead
Cannot retrieve channel.xml for channel "pear.php.net" (Connection to `ssl://pear.php.net:443' failed: )
Updating channel "pecl.php.net"
Channel "pecl.php.net" is up to date
```

Anybody any other ideas.

**Comment by kayintveen** [comment] 2019-11-24 11:50
I can update that its related to the valet-php version. 
Currently . installed php@7.1,  7.2 and such directly via brew and no issues with pecl. but that's an issue with valet of course.

**Comment by LucasMaliszewski** [comment] 2019-11-25 21:08
I can confirm that it doesn't work also on catalina.

**Comment by yusufdemir** [comment] 2019-12-01 16:30
I solved the problem. You must edit the last line of PECL.  
Add  -n attribute 
File
`/usr/local/Cellar/valet-php@7.1/7.1.33_2/bin/pecl`

OLD: $PHP -C -q 
`exec $PHP -C -q $INCARG -d date.timezone=UTC -d output_buffering=1 -d variables_order=EGPCS -d safe_mode=0 -d register_argc_argv="On" $INCDIR/peclcmd.php "$@"`

NEW: $PHP -C -n -q
`exec $PHP -C -n -q $INCARG -d date.timezone=UTC -d output_buffering=1 -d variables_order=EGPCS -d safe_mode=0 -d register_argc_argv="On" $INCDIR/peclcmd.php "$@"`

**Comment by Neodork** [comment] 2019-12-06 11:05
We're currently not able to reliably support Catalina because we don't have images for it yet on Azure DevOps.

Do you guys think this can be solved in our brew tap?

**Comment by Neodork** [comment] 2020-02-07 13:28
So I've determined the actual cause here being the new LibreSSL installation on MacOS catalina.

This installation has no cacert configured thus failing SSL connections. Applying the `-n` option as mentioned in this thread will cause the PHP binary to NOT use the php.ini. Thus circumventing the issue. But I would recommend to just configure your cacert.pem file.

**Comment by Neodork** [comment] 2020-02-07 14:54
Closing since it's a duplicate of https://github.com/weprovide/valet-plus/issues/457.

**Closed by Neodork** 2020-02-07 14:54 UTC
Labels: 2.x, Bug

**Comment by emirpprime** [comment] 2020-02-11 08:44
I had the same issue, and testing in a fresh install / Catalina VM verified that the issue is there too, and solved by @yusufdemir's solution (thanks @yusufdemir!)
