### ISSUE TITLE
Is it possible to set a PHP version for a specific domain?

### ISSUE THREAD

**Issue by kanduvisla** [weprovide/valet-plus#53] opened 2017-08-30 09:23 UTC
For example: can I set one domain / folder to run on PHP7.0 and the other on PHP7.1?

I understand that this can be quite challenging for the CLI, but is it possible to provide a preferred version number that is used with Nginx?

**Comment by timneutkens** [comment] 2017-08-30 14:33
Currently it's not possible. But this is a duplicate of https://github.com/weprovide/valet-plus/issues/26

**Closed by timneutkens** 2017-08-30 14:33 UTC
