### ISSUE TITLE
Mysql not in path -bash: mysql: command not found

### ISSUE THREAD

**Issue by SnowCommerceBrand** [weprovide/valet-plus#231] opened 2018-07-20 19:48 UTC
After running clean install I found that mysql could not be found. I added Mysql as below. I found this as a issue when trying to use magerun2. I get the following error:

-bash: mysql: command not found

Seems like Brew didn't add mysql to the path. I have brew setup and in my path. 
brew doctor 
Your system is ready to brew.

My fix was this and it worked but not sure if Mysql should have been added to path or not.
ln -sfn /usr/local/Cellar/mysql@5.7/5.7.22/bin/mysql /usr/local/bin/
ln -sfn /usr/local/Cellar/mysql@5.7/5.7.22/bin/mysqladmin /usr/local/bin/
ln -sfn /usr/local/Cellar/mysql@5.7/5.7.22/bin/Mysqld /usr/local/bin/

Valet+ 1.0.19
Homebrew 1.7.0-69-g7ad999f

**Comment by samgranger** [comment] 2018-08-02 07:39
Could you try running `brew link mysql@5.7 --force`? Hope that this solves your issue.

**Comment by utklasad** [comment] 2018-09-19 18:46
I'm having the same issue on three different machines. I first tought it was because we had some dev stuff installed before we tried Valet+ out but one of the machines was a completely new MacBook Pro without any dev stuff installed before we installed Valet+.

`brew link mysql@5.7 --force` fixed it on all the machines but there is definitely something wrong since it's so easy to reproduce. So thanks for that @samgranger

**Comment by MikeDynamic** [comment] 2018-11-28 11:46
I have the same problem, also on a new Mac running Mojave. 

Tried brew link mysql@5.7 --force but did not work. Also got brew saying it is ready to brew. 

Strange that I can access MySQL using mysql -uroot but the website I try and run say that the MySQL extension is required but if I run brew list is shows mysql@5.7

I have been through all of the forums and reinstalled time after time from scratch with Homebrew and valet and still the same issue... PHP server runs but cannot link to any database. I am at a complete loss :( 

Any suggestions?

**Comment by Neodork** [comment] 2020-02-07 11:22
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team

**Closed by Neodork** 2020-02-07 11:22 UTC
Labels: 1.0.x
